# https://hyprland-community.github.io/pyprland/

[pyprland]
    plugins = [ "scratchpads" ]
    notification_type = "auto"

[pyprland.variables]
    term_with_class = "kitty --class"

[scratchpads.console]
    # This is a drop-down terminal configuration
    animation = "fromTop"
    class     = "console-dropdown"
    command   = "[term_with_class] console-dropdown"
    max_size  = "90% 100%"
    size      = "75% 60%"


[scratchpads.rmpc]
    #Dropdown terminal with rmpc
    animation = "fromTop"
    class     = "rmpc"
    command   = "[term_with_class] rmpc-dropdown rmpc"
    max_size  = "90% 100%"
    size      = "75% 60%"
    lazy      = "true"
    unfocus   = "hide"
    close_on_hide = "true"

